# Generated by Django 5.0 on 2023-12-18 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deparment_store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategorydetails',
            old_name='categoryt_id',
            new_name='category_id',
        ),
    ]
